import db from "..";
import { advocates } from "../schema";
import { specialties } from "../specialties";

// Extract just the slugs for random selection
const specialtySlugs = specialties.map(s => s.slug);

const randomSpecialty = () => {
  const random1 = Math.floor(Math.random() * 24);
  const random2 = Math.floor(Math.random() * (24 - random1)) + random1 + 1;

  return [random1, random2];
};

const advocateData = [
  {
    firstName: "John",
    lastName: "Doe",
    city: "New York",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5551234567,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    city: "Los Angeles",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5559876543,
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    city: "Chicago",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5554567890,
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    city: "Houston",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5556543210,
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    city: "Phoenix",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5553210987,
  },
  {
    firstName: "Chris",
    lastName: "Martinez",
    city: "Philadelphia",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5557890123,
  },
  {
    firstName: "Jessica",
    lastName: "Taylor",
    city: "San Antonio",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5554561234,
  },
  {
    firstName: "David",
    lastName: "Harris",
    city: "San Diego",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5557896543,
  },
  {
    firstName: "Laura",
    lastName: "Clark",
    city: "Dallas",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5550123456,
  },
  {
    firstName: "Daniel",
    lastName: "Lewis",
    city: "San Jose",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5553217654,
  },
  {
    firstName: "Sarah",
    lastName: "Lee",
    city: "Austin",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5551238765,
  },
  {
    firstName: "James",
    lastName: "King",
    city: "Jacksonville",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5556540987,
  },
  {
    firstName: "Megan",
    lastName: "Green",
    city: "San Francisco",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 14,
    phoneNumber: 5559873456,
  },
  {
    firstName: "Joshua",
    lastName: "Walker",
    city: "Columbus",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5556781234,
  },
  {
    firstName: "Amanda",
    lastName: "Hall",
    city: "Fort Worth",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 3,
    phoneNumber: 5559872345,
  },
  {
    firstName: "Robert",
    lastName: "Wilson",
    city: "Seattle",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 15,
    phoneNumber: 5552348765,
  },
  {
    firstName: "Lisa",
    lastName: "Anderson",
    city: "Denver",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5558765432,
  },
  {
    firstName: "Mark",
    lastName: "Thompson",
    city: "Boston",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5551234987,
  },
  {
    firstName: "Rachel",
    lastName: "Garcia",
    city: "Miami",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5559876234,
  },
  {
    firstName: "Kevin",
    lastName: "Rodriguez",
    city: "Las Vegas",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5556789123,
  },
  {
    firstName: "Angela",
    lastName: "Miller",
    city: "Portland",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5553456789,
  },
  {
    firstName: "Brian",
    lastName: "Moore",
    city: "Nashville",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5557891234,
  },
  {
    firstName: "Stephanie",
    lastName: "Jackson",
    city: "Atlanta",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5552345678,
  },
  {
    firstName: "Ryan",
    lastName: "White",
    city: "Charlotte",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5558901234,
  },
  {
    firstName: "Nicole",
    lastName: "Thomas",
    city: "Tampa",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5554567123,
  },
  {
    firstName: "Gregory",
    lastName: "Martin",
    city: "Kansas City",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5557123456,
  },
  {
    firstName: "Michelle",
    lastName: "Lopez",
    city: "Raleigh",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5553789012,
  },
  {
    firstName: "Anthony",
    lastName: "Gonzalez",
    city: "Orlando",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 16,
    phoneNumber: 5556012345,
  },
  {
    firstName: "Kimberly",
    lastName: "Perez",
    city: "Sacramento",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5559012789,
  },
  {
    firstName: "Christopher",
    lastName: "Roberts",
    city: "Pittsburgh",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5552789456,
  },
  {
    firstName: "Jennifer",
    lastName: "Turner",
    city: "Cincinnati",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 14,
    phoneNumber: 5558456123,
  },
  {
    firstName: "Andrew",
    lastName: "Phillips",
    city: "Cleveland",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5551456789,
  },
  {
    firstName: "Amy",
    lastName: "Campbell",
    city: "St. Louis",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5554123789,
  },
  {
    firstName: "Scott",
    lastName: "Parker",
    city: "Minneapolis",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5557456012,
  },
  {
    firstName: "Rebecca",
    lastName: "Evans",
    city: "New Orleans",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5553012456,
  },
  {
    firstName: "Brandon",
    lastName: "Edwards",
    city: "Salt Lake City",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5556789012,
  },
  {
    firstName: "Melissa",
    lastName: "Collins",
    city: "Richmond",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 15,
    phoneNumber: 5559345678,
  },
  {
    firstName: "Justin",
    lastName: "Stewart",
    city: "Buffalo",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5552678901,
  },
  {
    firstName: "Heather",
    lastName: "Sanchez",
    city: "Norfolk",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5558123456,
  },
  {
    firstName: "Eric",
    lastName: "Morris",
    city: "Spokane",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5555678234,
  },
];

export { advocateData };
