import { specialties } from "../../types/specialties";

// Extract just the slugs for random selection
const specialtySlugs = specialties.map(s => s.slug);

const randomSpecialty = () => {
  const random1 = Math.floor(Math.random() * 24);
  const random2 = Math.floor(Math.random() * (24 - random1)) + random1 + 1;

  return [random1, random2];
};

const advocateData = [
  {
    firstName: "John",
    lastName: "Doe",
    city: "new-york",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5551234567,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    city: "los-angeles",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5559876543,
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    city: "chicago",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5554567890,
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    city: "houston",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5556543210,
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    city: "phoenix",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5553210987,
  },
  {
    firstName: "Chris",
    lastName: "Martinez",
    city: "philadelphia",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5557890123,
  },
  {
    firstName: "Jessica",
    lastName: "Taylor",
    city: "san-antonio",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5554561234,
  },
  {
    firstName: "David",
    lastName: "Harris",
    city: "san-diego",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5557896543,
  },
  {
    firstName: "Laura",
    lastName: "Clark",
    city: "dallas",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5550123456,
  },
  {
    firstName: "Daniel",
    lastName: "Lewis",
    city: "san-jose",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5553217654,
  },
  {
    firstName: "Sarah",
    lastName: "Lee",
    city: "austin",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5551238765,
  },
  {
    firstName: "James",
    lastName: "King",
    city: "jacksonville",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5556540987,
  },
  {
    firstName: "Megan",
    lastName: "Green",
    city: "san-francisco",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 14,
    phoneNumber: 5559873456,
  },
  {
    firstName: "Joshua",
    lastName: "Walker",
    city: "columbus",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5556781234,
  },
  {
    firstName: "Amanda",
    lastName: "Hall",
    city: "fort-worth",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 3,
    phoneNumber: 5559872345,
  },
  {
    firstName: "Robert",
    lastName: "Wilson",
    city: "seattle",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 15,
    phoneNumber: 5552348765,
  },
  {
    firstName: "Lisa",
    lastName: "Anderson",
    city: "denver",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5558765432,
  },
  {
    firstName: "Mark",
    lastName: "Thompson",
    city: "boston",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5551234987,
  },
  {
    firstName: "Rachel",
    lastName: "Garcia",
    city: "miami",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5559876234,
  },
  {
    firstName: "Kevin",
    lastName: "Rodriguez",
    city: "las-vegas",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5556789123,
  },
  {
    firstName: "Angela",
    lastName: "Miller",
    city: "portland",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5553456789,
  },
  {
    firstName: "Brian",
    lastName: "Moore",
    city: "nashville",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5557891234,
  },
  {
    firstName: "Stephanie",
    lastName: "Jackson",
    city: "atlanta",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5552345678,
  },
  {
    firstName: "Ryan",
    lastName: "White",
    city: "charlotte",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5558901234,
  },
  {
    firstName: "Nicole",
    lastName: "Thomas",
    city: "tampa",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5554567123,
  },
  {
    firstName: "Gregory",
    lastName: "Martin",
    city: "kansas-city",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5557123456,
  },
  {
    firstName: "Michelle",
    lastName: "Lopez",
    city: "raleigh",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5553789012,
  },
  {
    firstName: "Anthony",
    lastName: "Gonzalez",
    city: "orlando",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 16,
    phoneNumber: 5556012345,
  },
  {
    firstName: "Kimberly",
    lastName: "Perez",
    city: "sacramento",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5559012789,
  },
  {
    firstName: "Christopher",
    lastName: "Roberts",
    city: "pittsburgh",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5552789456,
  },
  {
    firstName: "Jennifer",
    lastName: "Turner",
    city: "cincinnati",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 14,
    phoneNumber: 5558456123,
  },
  {
    firstName: "Andrew",
    lastName: "Phillips",
    city: "cleveland",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5551456789,
  },
  {
    firstName: "Amy",
    lastName: "Campbell",
    city: "st-louis",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5554123789,
  },
  {
    firstName: "Scott",
    lastName: "Parker",
    city: "minneapolis",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5557456012,
  },
  {
    firstName: "Rebecca",
    lastName: "Evans",
    city: "new-orleans",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5553012456,
  },
  {
    firstName: "Brandon",
    lastName: "Edwards",
    city: "salt-lake-city",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5556789012,
  },
  {
    firstName: "Melissa",
    lastName: "Collins",
    city: "richmond",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 15,
    phoneNumber: 5559345678,
  },
  {
    firstName: "Justin",
    lastName: "Stewart",
    city: "buffalo",
    degree: "PhD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5552678901,
  },
  {
    firstName: "Heather",
    lastName: "Sanchez",
    city: "norfolk",
    degree: "MSW",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5558123456,
  },
  {
    firstName: "Eric",
    lastName: "Morris",
    city: "spokane",
    degree: "MD",
    specialties: specialtySlugs.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5555678234,
  },
];

export { advocateData };
